"""added country, customer, account, transaction, and user

Revision ID: 08191c50671d
Revises: 
Create Date: 2024-01-29 10:58:02.740448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08191c50671d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Countries',
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('telephone_country_code', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('country_code')
    )
    op.create_table('Customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('postal_code', sa.String(length=10), nullable=False),
    sa.Column('birthday', sa.DateTime(), nullable=False),
    sa.Column('national_id', sa.String(length=20), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('country', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Users',
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=7), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('Accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_type', sa.String(length=10), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['Customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('operation', sa.String(length=50), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('new_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['Accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Transactions')
    op.drop_table('Accounts')
    op.drop_table('Users')
    op.drop_table('Customers')
    op.drop_table('Countries')
    # ### end Alembic commands ###
