"""removed operations from transaction table

Revision ID: 16fdaefa6801
Revises: 7babadd039e4
Create Date: 2024-01-31 08:32:10.901789

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '16fdaefa6801'
down_revision = '7babadd039e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Transactions', schema=None) as batch_op:
        batch_op.drop_column('operation')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('operation', mysql.VARCHAR(length=50), nullable=False))

    # ### end Alembic commands ###
