"""changed country in customer table to be foreign key

Revision ID: 40239e1a20f0
Revises: 08191c50671d
Create Date: 2024-01-29 11:21:28.290178

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '40239e1a20f0'
down_revision = '08191c50671d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Customers', schema=None) as batch_op:
        batch_op.alter_column('country',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=2),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'Countries', ['country'], ['country_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Customers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('country',
               existing_type=sa.String(length=2),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
