"""added checked col to transaction

Revision ID: 482de1e83725
Revises: bb659765197a
Create Date: 2024-02-21 10:15:16.442674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '482de1e83725'
down_revision = 'bb659765197a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checked', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Transactions', schema=None) as batch_op:
        batch_op.drop_column('checked')

    # ### end Alembic commands ###
