"""changed account created from datetime to date

Revision ID: 9366e46f6b03
Revises: d5388399eb34
Create Date: 2024-01-29 13:24:04.595749

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9366e46f6b03'
down_revision = 'd5388399eb34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Accounts', schema=None) as batch_op:
        batch_op.alter_column('created',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Accounts', schema=None) as batch_op:
        batch_op.alter_column('created',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
