"""reverted to multiple roles

Revision ID: ca17ddc63954
Revises: f922b0e37f61
Create Date: 2024-02-28 12:39:36.823865

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ca17ddc63954'
down_revision = 'f922b0e37f61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('RolesUsers',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['Roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], )
    )
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_constraint('Users_ibfk_1', type_='foreignkey')
        batch_op.drop_column('role_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('Users_ibfk_1', 'Roles', ['role_id'], ['id'])

    op.drop_table('RolesUsers')
    # ### end Alembic commands ###
